name: Build and Push Docker Images to an ECR

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  test:
    name: Testing on Release Published and Manual Trigger
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update Task Definition
        run: "echo Good Craic"
